name: exceptions in hydration call that fail with errors are reflected in the result
enabled:
  current: true
  nextgen: true
overallSchema:
  Bar: |
    service Bar {
      type Query {
        bar: Bar
      }
      type Bar {
        name: String
        nestedBar: Bar => hydrated from Bar.barById(id: $source.nestedBarId)
      }
    }
  Foo: |
    service Foo {
      type Query {
        foo: Foo
      }
      type Foo {
        name: String
        bar: Bar => hydrated from Bar.barById(id: $source.barId)
      }
    }
underlyingSchema:
  Bar: |
    type Bar {
      id: ID
      name: String
      nestedBarId: ID
    }

    type Query {
      bar: Bar
      barById(id: ID): Bar
    }
  Foo: |
    type Foo {
      barId: ID
      name: String
    }

    type Query {
      foo: Foo
    }
query: |
  query {
    foo {
      bar {
        name
        nestedBar {
          name
          nestedBar {
            name
          }
        }
      }
    }
  }
variables: {}
serviceCalls:
  current:
    - serviceName: Foo
      request:
        query: |
          query nadel_2_Foo {
            foo {
              barId
            }
          }
        variables: {}
        operationName: nadel_2_Foo
      response: |-
        {
          "data": {
            "foo": {
              "barId": "barId123"
            }
          },
          "extensions": {}
        }
# language=JSON
response: null
